---
core: &core
  xaasio-cmp/xaasio-cmp:
  xaasio-cmp/xaasio-api:
  xaasio-cmp/xaasio-automation_engine:
  xaasio-cmp/xaasio-consumption:
  xaasio-cmp/xaasio-content:
  xaasio-cmp/xaasio-decorators:
  xaasio-cmp/xaasio-gems-pending:
  xaasio-cmp/xaasio-schema:
  xaasio-cmp/xaasio-ui-classic:
  xaasio-cmp/xaasio-ui-service:
providers: &providers
  xaasio-cmp/xaasio-providers-amazon:
  xaasio-cmp/xaasio-providers-ansible_tower:
  xaasio-cmp/xaasio-providers-autosde:
  xaasio-cmp/xaasio-providers-awx:
  xaasio-cmp/xaasio-providers-azure:
  xaasio-cmp/xaasio-providers-azure_stack:
  xaasio-cmp/xaasio-providers-cisco_intersight:
  xaasio-cmp/xaasio-providers-embedded_terraform:
  xaasio-cmp/xaasio-providers-foreman:
  xaasio-cmp/xaasio-providers-google:
  xaasio-cmp/xaasio-providers-ibm_cic:
  xaasio-cmp/xaasio-providers-ibm_cloud:
  xaasio-cmp/xaasio-providers-ibm_power_hmc:
  xaasio-cmp/xaasio-providers-ibm_power_vc:
  xaasio-cmp/xaasio-providers-ibm_terraform:
  xaasio-cmp/xaasio-providers-kubernetes:
  xaasio-cmp/xaasio-providers-kubevirt:
  xaasio-cmp/xaasio-providers-lenovo:
  xaasio-cmp/xaasio-providers-nsxt:
  xaasio-cmp/xaasio-providers-nuage:
  xaasio-cmp/xaasio-providers-nutanix:
  xaasio-cmp/xaasio-providers-openshift:
  xaasio-cmp/xaasio-providers-openstack:
  xaasio-cmp/xaasio-providers-oracle_cloud:
  xaasio-cmp/xaasio-providers-ovirt:
  xaasio-cmp/xaasio-providers-red_hat_virtualization:
  xaasio-cmp/xaasio-providers-redfish:
  xaasio-cmp/xaasio-providers-terraform_enterprise:
  xaasio-cmp/xaasio-providers-vmware:
  xaasio-cmp/xaasio-providers-workflows:
all:
  <<:
  - *core
  - *providers
