gems:
  ManageIQ/activerecord-id_regions:
  ManageIQ/activerecord-virtual_attributes:
  ManageIQ/amazon_ssa_support:
  ManageIQ/awesome_spawn:
  ManageIQ/azure-armrest:
  ManageIQ/azure-signature:
  ManageIQ/binary_struct:
  ManageIQ/bundler-inject:
  ManageIQ/ffi-vix_disk_lib:
  ManageIQ/floe:
  ManageIQ/foreman_api_client:
  ManageIQ/httpd_configmap_generator:
  ManageIQ/inventory_refresh:
  ManageIQ/linux_admin:
  ManageIQ/linux_block_device:
  ManageIQ/log_decorator:
  ManageIQ/manageiq-api-client:
  ManageIQ/manageiq-appliance_console:
  ManageIQ/manageiq-cross_repo:
  ManageIQ/manageiq-loggers:
  ManageIQ/manageiq-messaging:
  ManageIQ/manageiq-password:
  ManageIQ/manageiq-postgres_ha_admin:
  ManageIQ/manageiq-smartstate:
  ManageIQ/manageiq-ssh-util:
  ManageIQ/manageiq-style:
  ManageIQ/memory_buffer:
  ManageIQ/mime-types-redirector:
  ManageIQ/more_core_extensions:
  ManageIQ/multi_repo:
  ManageIQ/net_app_manageability:
  ManageIQ/optimist:
  ManageIQ/ovirt:
  ManageIQ/ovirt_metrics:
  ManageIQ/pg-dsn_parser:
  ManageIQ/pg-logical_replication:
  ManageIQ/pg-pglogical:
  ManageIQ/query_relation:
  ManageIQ/rbvmomi2:
  ManageIQ/ruby-rpm-ffi2:
  ManageIQ/vmware_web_service:
  ManageIQ/wim_parser:
applications:
  ManageIQ/dbus_api_service:
  ManageIQ/miq_bot:
tools:
  ManageIQ/manageiq-appliance:
  ManageIQ/manageiq-appliance-build:
  ManageIQ/manageiq-performance:
  ManageIQ/manageiq-providers-dummy_provider:
  ManageIQ/manageiq-release:
  ManageIQ/manageiq-rpm_build:
