gems:
  activerecord-id_regions:
  activerecord-virtual_attributes:
  amazon_ssa_support:
  awesome_spawn:
  azure-armrest:
  azure-signature:
  binary_struct:
  bundler-inject:
  ffi-vix_disk_lib:
  foreman_api_client:
  httpd_configmap_generator:
  inventory_refresh:
  linux_admin:
  linux_block_device:
  log_decorator:
  manageiq-api-client:
  manageiq-appliance_console:
  manageiq-cross_repo:
  manageiq-loggers:
  manageiq-messaging:
  manageiq-password:
  manageiq-postgres_ha_admin:
  manageiq-smartstate:
  manageiq-ssh-util:
  manageiq-style:
  memory_buffer:
  mime-types-redirector:
  more_core_extensions:
  multi_repo:
  net_app_manageability:
  optimist:
  ovirt:
  ovirt_metrics:
  pg-dsn_parser:
  pg-logical_replication:
  pg-pglogical:
  query_relation:
  vmware_web_service:
  wim_parser:
applications:
  dbus_api_service:
  miq_bot:
tools:
  manageiq-appliance:
  manageiq-appliance-build:
  manageiq-performance:
  manageiq-providers-dummy_provider:
  manageiq-release:
  manageiq-rpm_build:
