---
:git_mirror:
  :branch_mirror_defaults: {}
  :branch_mirror_overrides:
    # container repos don't follow branch naming conventions, so don't mirror master to a release branch
    # and also include any container-specific branches directly
    container-httpd:
      2-el8:
      2-el9:
      2-el10:
      master:
    container-memcached:
      1-el8:
      1-el9:
      1-el10:
      master:
    container-postgresql:
      10-el8:
      13-el8:
      13-el9:
      16-el10:
      master:
    # The following repos don't have release branches, so don't mirror master to a release branch
    manageiq-release:
      master:
  :productization_name: manageiq
  :remotes:
    :upstream: git@github.com:ManageIQ
  :repos_to_mirror:
    container-httpd:
    container-memcached:
    container-postgresql:
    manageiq-api:
    manageiq-appliance-build:
    manageiq-appliance:
    manageiq-automation_engine:
    manageiq-consumption:
    manageiq-content:
    manageiq-decorators:
    manageiq-documentation:
    manageiq-gems-pending:
    manageiq-pods:
    manageiq-providers-amazon:
    manageiq-providers-ansible_tower:
    manageiq-providers-autosde:
    manageiq-providers-awx:
    manageiq-providers-azure:
    manageiq-providers-azure_stack:
    manageiq-providers-cisco_intersight:
    manageiq-providers-embedded_terraform:
    manageiq-providers-foreman:
    manageiq-providers-google:
    manageiq-providers-ibm_cic:
    manageiq-providers-ibm_cloud:
    manageiq-providers-ibm_power_hmc:
    manageiq-providers-ibm_power_vc:
    manageiq-providers-ibm_terraform:
    manageiq-providers-kubernetes:
    manageiq-providers-kubevirt:
    manageiq-providers-lenovo:
    manageiq-providers-nsxt:
    manageiq-providers-nuage:
    manageiq-providers-nutanix:
    manageiq-providers-openshift:
    manageiq-providers-openstack:
    manageiq-providers-oracle_cloud:
    manageiq-providers-ovirt:
    manageiq-providers-proxmox:
    manageiq-providers-red_hat_virtualization:
    manageiq-providers-redfish:
    manageiq-providers-terraform_enterprise:
    manageiq-providers-vmware:
    manageiq-providers-workflows:
    manageiq-release:
    manageiq-schema:
    manageiq-ui-classic:
    manageiq-ui-service:
    manageiq:
  :working_directory: mirrors
:manageiq_rubygems:
  :s3_access_key:
  :s3_secret_key:
  :s3_endpoint: https://s3.us-east.cloud-object-storage.appdomain.cloud
  :s3_bucket: rubygems-manageiq-org
  :s3_region: us-east
