---
:git_mirror:
  :branch_mirror_defaults: {}
  :branch_mirror_overrides:
    # container repos don't follow branch naming conventions, so don't mirror master to a release branch
    # and also include any container-specific branches directly
    container-httpd:
      master:
    container-memcached:
      master:
    container-postgresql:
      master:
      10-el8:
    # The following repos don't have release branches, so don't mirror master to a release branch
    manageiq-release:
      master:
    # The following repos have been removed as a plugin starting with najdorf, so don't mirror master to a najdorf+ release branch
    manageiq-graphql:
      master:
    manageiq-v2v:
      master:
  :productization_name: xaasio-cmp
  :remotes:
    :upstream: git@github.com:ManageIQ
    :downstream: https://gitlab.xaasio.com/xaasio-cmp
  :repos_to_mirror:
    container-httpd:
    container-memcached:
    container-postgresql:
    xaasio-api:
    xaasio-appliance-build:
    xaasio-appliance:
    xaasio-automation_engine:
    xaasio-consumption:
    xaasio-content:
    xaasio-decorators:
    xaasio-documentation:
    xaasio-gems-pending:
    # xaasio-graphql has been removed as a plugin starting with najdorf, but we still need to mirror other branches
    xaasio-graphql:
    xaasio-pods:
    xaasio-providers-amazon:
    xaasio-providers-ansible_tower:
    xaasio-providers-autosde:
    xaasio-providers-awx:
    xaasio-providers-azure:
    xaasio-providers-azure_stack:
    xaasio-providers-cisco_intersight:
    xaasio-providers-embedded_terraform:
    xaasio-providers-foreman:
    xaasio-providers-google:
    xaasio-providers-ibm_cic:
    xaasio-providers-ibm_cloud:
    xaasio-providers-ibm_power_hmc:
    xaasio-providers-ibm_power_vc:
    xaasio-providers-ibm_terraform:
    xaasio-providers-kubernetes:
    xaasio-providers-kubevirt:
    xaasio-providers-lenovo:
    xaasio-providers-nsxt:
    xaasio-providers-nuage:
    xaasio-providers-nutanix:
    xaasio-providers-openshift:
    xaasio-providers-openstack:
    xaasio-providers-oracle_cloud:
    xaasio-providers-ovirt:
    xaasio-providers-red_hat_virtualization:
    xaasio-providers-redfish:
    xaasio-providers-terraform_enterprise:
    xaasio-providers-vmware:
    xaasio-providers-workflows:
    xaasio-release:
    xaasio-schema:
    xaasio-ui-classic:
    xaasio-ui-service:
    # xaasio-v2v has been removed as a plugin starting with najdorf, but we still need to mirror other branches
    xaasio-v2v:
    xaasio-cmp:
  :working_directory: mirrors
:manageiq_rubygems:
  :s3_access_key:
  :s3_secret_key:
  :s3_endpoint: https://s3.us-east.cloud-object-storage.appdomain.cloud
  :s3_bucket: rubygems-manageiq-org
  :s3_region: us-east
